language: c

compiler:
  - gcc
  - clang

before_install:
  - uname -a
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y check
  - sudo apt-get install -y automake
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y autoconf-archive
  - sudo apt-get install -y libtool
  - cd `mktemp -d`
  - wget http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.xz
  - tar vxJf automake-1.14.1.tar.xz
  - cd automake-1.14.1
  - ./configure && make && sudo make install
  - cd `mktemp -d`
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz
  - tar vxJf autoconf-2.69.tar.xz
  - cd autoconf-2.69
  - ./configure && make && sudo make install
  - cd `mktemp -d`
  - wget http://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2014.02.28.tar.xz
  - tar vxJf autoconf-archive-2014.02.28.tar.xz
  - cd autoconf-archive-2014.02.28
  - ./configure && make && sudo make install


before_script:
  - env | sort
  - which autoconf && autoconf --version
  - which automake && automake --version
  - which libtool  && libtool  --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - mkdir -vp m4
  - mkdir -vp _build
  - cd _build
  - autoreconf -ivf ..
  - ../configure
  - make
  - make check
  - make distcheck

