language: c

compiler:
  - gcc
  - clang

before_install:
  - uname -a
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y check
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y autoconf-archive
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool

before_script:
  - env | sort
  - autoconf --version
  - automake --version
  - libtool --version

script:
  - pwd
  - mkdir -vp m4
  - mkdir -vp _build
  - cd _build
  - autoreconf -ivf ..
  - ../configure --prefix=/tmp/the-prefix
  - make
  - make check
  - make distcheck

