language: c

compiler:
  - gcc
  - clang

before_install:
  - uname -a
  - pwd
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y check
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y autoconf-archive
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool

before_script:
  - mkdir -vp _build
  - cd _build

script:
  - autoreconf -ivf ..
  - ../configure --prefix=/tmp/foobar
  - make
  - make check
  - make distcheck

